//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCDbEntities : DbContext
    {
        public SCDbEntities()
            : base("name=SCDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<l_Group_Menu> l_Group_Menu { get; set; }
        public virtual DbSet<sys_Menu> sys_Menu { get; set; }
        public virtual DbSet<sys_User> sys_User { get; set; }
        public virtual DbSet<sys_User_Group> sys_User_Group { get; set; }
    }
}
